config/routes.rb
Epitool::Application.routes.draw do
  resources :r_property_definitions

  resources :r_pages_to_entries

  resources :r_contacts

  resources :r_pages

  resources :r_entries_to_links

  resources :r_links

  resources :r_entries

  resources :r_languages

	root 'main#home'

  

  
  
end

app/models/r_pages_to_entry.rb
class RPagesToEntry < ActiveRecord::Base
  belongs_to :r_page
  belongs_to :r_entry
end

app/controllers/r_pages_to_entries_controller.rb
class RPagesToEntriesController < ApplicationController
  before_action :set_r_pages_to_entry, only: [:show, :edit, :update, :destroy]

  # GET /r_pages_to_entries
  # GET /r_pages_to_entries.json
  def index
    @r_pages_to_entries = RPagesToEntry.all
  end

  # GET /r_pages_to_entries/1
  # GET /r_pages_to_entries/1.json
  def show
  end

  # GET /r_pages_to_entries/new
  def new
    @r_pages_to_entry = RPagesToEntry.new
  end

  # GET /r_pages_to_entries/1/edit
  def edit
  end

  # POST /r_pages_to_entries
  # POST /r_pages_to_entries.json
  def create
    @r_pages_to_entry = RPagesToEntry.new(r_pages_to_entry_params)

    respond_to do |format|
      if @r_pages_to_entry.save
        format.html { redirect_to @r_pages_to_entry, notice: 'R pages to entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @r_pages_to_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @r_pages_to_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /r_pages_to_entries/1
  # PATCH/PUT /r_pages_to_entries/1.json
  def update
    respond_to do |format|
      if @r_pages_to_entry.update(r_pages_to_entry_params)
        format.html { redirect_to @r_pages_to_entry, notice: 'R pages to entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @r_pages_to_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /r_pages_to_entries/1
  # DELETE /r_pages_to_entries/1.json
  def destroy
    @r_pages_to_entry.destroy
    respond_to do |format|
      format.html { redirect_to r_pages_to_entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_r_pages_to_entry
      @r_pages_to_entry = RPagesToEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def r_pages_to_entry_params
      params.require(:r_pages_to_entry).permit(:r_page_id, :r_entry_id, :properties)
    end
end

app/helpers/r_pages_to_entries_helper.rb
module RPagesToEntriesHelper
end

app/views/r_pages_to_entries/_form.html.erb
<%= form_for(@r_pages_to_entry) do |f| %>
  <% if @r_pages_to_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@r_pages_to_entry.errors.count, "error") %> prohibited this r_pages_to_entry from being saved:</h2>

      <ul>
      <% @r_pages_to_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :r_page_id %><br>
    <%= f.select :r_page_id, options_from_collection_for_select(RPage.all, 'id', 'name') %>
  </div>
  <div class="field">
    <%= f.label :r_entry_id %><br>
    <%= f.select :r_entry_id, options_from_collection_for_select(REntry.all, 'id', 'title') %>
  </div>
  <div class="field">
    <%= f.label :properties %><br>
    <%= f.text_field :properties %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/r_pages_to_entries/edit.html.erb
<h1>Editing r_pages_to_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @r_pages_to_entry %> |
<%= link_to 'Back', r_pages_to_entries_path %>

app/views/r_pages_to_entries/index.html.erb
<h1>Listing r_pages_to_entries</h1>

<table>
  <thead>
    <tr>
      <th>R page</th>
      <th>R entry</th>
      <th>Properties</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @r_pages_to_entries.each do |r_pages_to_entry| %>
      <tr>
        <td><%= r_pages_to_entry.r_page_id %></td>
        <td><%= r_pages_to_entry.r_entry_id %></td>
        <td><%= r_pages_to_entry.properties %></td>
        <td><%= link_to 'Show', r_pages_to_entry %></td>
        <td><%= link_to 'Edit', edit_r_pages_to_entry_path(r_pages_to_entry) %></td>
        <td><%= link_to 'Destroy', r_pages_to_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New R pages to entry', new_r_pages_to_entry_path %>

app/views/r_pages_to_entries/new.html.erb
<h1>New r_pages_to_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', r_pages_to_entries_path %>

app/views/r_pages_to_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>R page:</strong>
  <%= @r_pages_to_entry.r_page_id %>
</p>

<p>
  <strong>R entry:</strong>
  <%= @r_pages_to_entry.r_entry_id %>
</p>

<p>
  <strong>Properties:</strong>
  <%= @r_pages_to_entry.properties %>
</p>

<%= link_to 'Edit', edit_r_pages_to_entry_path(@r_pages_to_entry) %> |
<%= link_to 'Back', r_pages_to_entries_path %>