config/routes.rb
Epitool::Application.routes.draw do
  resources :r_property_definitions

  resources :r_pages_to_entries

  resources :r_contacts

  resources :r_pages

  resources :r_entries_to_links

  resources :r_links

  resources :r_entries

  resources :r_languages

	root 'main#home'

  

  
  
end

app/models/r_entries_to_link.rb
class REntriesToLink < ActiveRecord::Base
end

app/controllers/r_entries_to_links_controller.rb
class REntriesToLinksController < ApplicationController
  before_action :set_r_entries_to_link, only: [:show, :edit, :update, :destroy]

  # GET /r_entries_to_links
  # GET /r_entries_to_links.json
  def index
    @r_entries_to_links = REntriesToLink.all
  end

  # GET /r_entries_to_links/1
  # GET /r_entries_to_links/1.json
  def show
  end

  # GET /r_entries_to_links/new
  def new
    @r_entries_to_link = REntriesToLink.new
  end

  # GET /r_entries_to_links/1/edit
  def edit
  end

  # POST /r_entries_to_links
  # POST /r_entries_to_links.json
  def create
    @r_entries_to_link = REntriesToLink.new(r_entries_to_link_params)

    respond_to do |format|
      if @r_entries_to_link.save
        format.html { redirect_to @r_entries_to_link, notice: 'R entries to link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @r_entries_to_link }
      else
        format.html { render action: 'new' }
        format.json { render json: @r_entries_to_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /r_entries_to_links/1
  # PATCH/PUT /r_entries_to_links/1.json
  def update
    respond_to do |format|
      if @r_entries_to_link.update(r_entries_to_link_params)
        format.html { redirect_to @r_entries_to_link, notice: 'R entries to link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @r_entries_to_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /r_entries_to_links/1
  # DELETE /r_entries_to_links/1.json
  def destroy
    @r_entries_to_link.destroy
    respond_to do |format|
      format.html { redirect_to r_entries_to_links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_r_entries_to_link
      @r_entries_to_link = REntriesToLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def r_entries_to_link_params
      params.require(:r_entries_to_link).permit(:r_entry_id, :r_link_id, :properties)
    end
end

app/helpers/r_entries_to_links_helper.rb
module REntriesToLinksHelper
end

app/views/r_entries_to_links/_form.html.erb
<%= form_for(@r_entries_to_link) do |f| %>
  <% if @r_entries_to_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@r_entries_to_link.errors.count, "error") %> prohibited this r_entries_to_link from being saved:</h2>

      <ul>
      <% @r_entries_to_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :r_entry_id %><br>
    <%= f.number_field :r_entry_id %>
  </div>
  <div class="field">
    <%= f.label :r_link_id %><br>
    <%= f.number_field :r_link_id %>
  </div>
  <div class="field">
    <%= f.label :properties %><br>
    <%= f.text_field :properties %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/r_entries_to_links/edit.html.erb
<h1>Editing r_entries_to_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @r_entries_to_link %> |
<%= link_to 'Back', r_entries_to_links_path %>

app/views/r_entries_to_links/index.html.erb
<h1>Listing r_entries_to_links</h1>

<table>
  <thead>
    <tr>
      <th>R entry</th>
      <th>R link</th>
      <th>Properties</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @r_entries_to_links.each do |r_entries_to_link| %>
      <tr>
        <td><%= r_entries_to_link.r_entry_id %></td>
        <td><%= r_entries_to_link.r_link_id %></td>
        <td><%= r_entries_to_link.properties %></td>
        <td><%= link_to 'Show', r_entries_to_link %></td>
        <td><%= link_to 'Edit', edit_r_entries_to_link_path(r_entries_to_link) %></td>
        <td><%= link_to 'Destroy', r_entries_to_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New R entries to link', new_r_entries_to_link_path %>

app/views/r_entries_to_links/new.html.erb
<h1>New r_entries_to_link</h1>

<%= render 'form' %>

<%= link_to 'Back', r_entries_to_links_path %>

app/views/r_entries_to_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>R entry:</strong>
  <%= @r_entries_to_link.r_entry_id %>
</p>

<p>
  <strong>R link:</strong>
  <%= @r_entries_to_link.r_link_id %>
</p>

<p>
  <strong>Properties:</strong>
  <%= @r_entries_to_link.properties %>
</p>

<%= link_to 'Edit', edit_r_entries_to_link_path(@r_entries_to_link) %> |
<%= link_to 'Back', r_entries_to_links_path %>