config/routes.rb
Epitool::Application.routes.draw do
  resources :r_property_definitions

  resources :r_pages_to_entries

  resources :r_contacts

  resources :r_pages

  resources :r_entries_to_links

  resources :r_links

  resources :r_entries

  resources :r_languages

	root 'main#home'

  

  
  
end

app/models/r_contact.rb
class RContact < ActiveRecord::Base
end

app/controllers/r_contacts_controller.rb
class RContactsController < ApplicationController
  before_action :set_r_contact, only: [:show, :edit, :update, :destroy]

  # GET /r_contacts
  # GET /r_contacts.json
  def index
    @r_contacts = RContact.all
  end

  # GET /r_contacts/1
  # GET /r_contacts/1.json
  def show
  end

  # GET /r_contacts/new
  def new
    @r_contact = RContact.new
  end

  # GET /r_contacts/1/edit
  def edit
  end

  # POST /r_contacts
  # POST /r_contacts.json
  def create
    @r_contact = RContact.new(r_contact_params)

    respond_to do |format|
      if @r_contact.save
        format.html { redirect_to @r_contact, notice: 'R contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @r_contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @r_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /r_contacts/1
  # PATCH/PUT /r_contacts/1.json
  def update
    respond_to do |format|
      if @r_contact.update(r_contact_params)
        format.html { redirect_to @r_contact, notice: 'R contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @r_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /r_contacts/1
  # DELETE /r_contacts/1.json
  def destroy
    @r_contact.destroy
    respond_to do |format|
      format.html { redirect_to r_contacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_r_contact
      @r_contact = RContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def r_contact_params
      params.require(:r_contact).permit(:name, :profession, :email, :properties)
    end
end

app/helpers/r_contacts_helper.rb
module RContactsHelper
end

app/views/r_contacts/_form.html.erb
<%= form_for(@r_contact) do |f| %>
  <% if @r_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@r_contact.errors.count, "error") %> prohibited this r_contact from being saved:</h2>

      <ul>
      <% @r_contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :profession %><br>
    <%= f.text_field :profession %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :properties %><br>
    <%= f.text_field :properties %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/r_contacts/edit.html.erb
<h1>Editing r_contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @r_contact %> |
<%= link_to 'Back', r_contacts_path %>

app/views/r_contacts/index.html.erb
<h1>Listing r_contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Profession</th>
      <th>Email</th>
      <th>Properties</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @r_contacts.each do |r_contact| %>
      <tr>
        <td><%= r_contact.name %></td>
        <td><%= r_contact.profession %></td>
        <td><%= r_contact.email %></td>
        <td><%= r_contact.properties %></td>
        <td><%= link_to 'Show', r_contact %></td>
        <td><%= link_to 'Edit', edit_r_contact_path(r_contact) %></td>
        <td><%= link_to 'Destroy', r_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New R contact', new_r_contact_path %>

app/views/r_contacts/new.html.erb
<h1>New r_contact</h1>

<%= render 'form' %>

<%= link_to 'Back', r_contacts_path %>

app/views/r_contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @r_contact.name %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @r_contact.profession %>
</p>

<p>
  <strong>Email:</strong>
  <%= @r_contact.email %>
</p>

<p>
  <strong>Properties:</strong>
  <%= @r_contact.properties %>
</p>

<%= link_to 'Edit', edit_r_contact_path(@r_contact) %> |
<%= link_to 'Back', r_contacts_path %>