config/routes.rb
Epitool::Application.routes.draw do
  resources :r_property_definitions

  resources :r_pages_to_entries

  resources :r_contacts

  resources :r_pages

  resources :r_entries_to_links

  resources :r_links

  resources :r_entries

  resources :r_languages

	root 'main#home'

  

  
  
end

app/models/r_language.rb
class RLanguage < ActiveRecord::Base
  has_many :r_pages
  has_many :r_entries
end

app/controllers/r_languages_controller.rb
class RLanguagesController < ApplicationController
  before_action :set_r_language, only: [:show, :edit, :update, :destroy]

  # GET /r_languages
  # GET /r_languages.json
  def index
    @r_languages = RLanguage.all
  end

  # GET /r_languages/1
  # GET /r_languages/1.json
  def show
  end

  # GET /r_languages/new
  def new
    @r_language = RLanguage.new
  end

  # GET /r_languages/1/edit
  def edit
  end

  # POST /r_languages
  # POST /r_languages.json
  def create
    @r_language = RLanguage.new(r_language_params)

    respond_to do |format|
      if @r_language.save
        format.html { redirect_to @r_language, notice: 'R language was successfully created.' }
        format.json { render action: 'show', status: :created, location: @r_language }
      else
        format.html { render action: 'new' }
        format.json { render json: @r_language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /r_languages/1
  # PATCH/PUT /r_languages/1.json
  def update
    respond_to do |format|
      if @r_language.update(r_language_params)
        format.html { redirect_to @r_language, notice: 'R language was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @r_language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /r_languages/1
  # DELETE /r_languages/1.json
  def destroy
    @r_language.destroy
    respond_to do |format|
      format.html { redirect_to r_languages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_r_language
      @r_language = RLanguage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def r_language_params
      params.require(:r_language).permit(:language, :properties)
    end
end

app/helpers/r_languages_helper.rb
module RLanguagesHelper
end

app/views/r_languages/_form.html.erb
<%= form_for(@r_language) do |f| %>
  <% if @r_language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@r_language.errors.count, "error") %> prohibited this r_language from being saved:</h2>

      <ul>
      <% @r_language.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :properties %><br>
    <%= f.text_field :properties %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/r_languages/edit.html.erb
<h1>Editing r_language</h1>

<%= render 'form' %>

<%= link_to 'Show', @r_language %> |
<%= link_to 'Back', r_languages_path %>

app/views/r_languages/index.html.erb
<h1>Listing r_languages</h1>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th>Properties</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @r_languages.each do |r_language| %>
      <tr>
        <td><%= r_language.language %></td>
        <td><%= r_language.properties %></td>
        <td><%= link_to 'Show', r_language %></td>
        <td><%= link_to 'Edit', edit_r_language_path(r_language) %></td>
        <td><%= link_to 'Destroy', r_language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New R language', new_r_language_path %>

app/views/r_languages/new.html.erb
<h1>New r_language</h1>

<%= render 'form' %>

<%= link_to 'Back', r_languages_path %>

app/views/r_languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= @r_language.language %>
</p>

<p>
  <strong>Properties:</strong>
  <%= @r_language.properties %>
</p>

<%= link_to 'Edit', edit_r_language_path(@r_language) %> |
<%= link_to 'Back', r_languages_path %>